#This script is for GitAction Practical 
#Date : 27/02/2026


name: CI Test

on: push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Step 1 - Download repo code
        uses: actions/checkout@v4

      - name: Step 2 - Show Files
        run: ls -la

      - name: Step 3 - Print Success Message
        run: echo "YOU HAVE PASSED THE TEST!!!!"

