#This script is for GitAction Practical 
#Date : 27/02/2026


name: CI Test

on: 
  push:
    branches:
      - Ci-Cd

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Step 1 - Checkout code 
        uses: actions/checkout@v4

      - name: Step 2 - Show Files
        run: ls -la

      - name: Step 3 - Build Docker Image
        run: docker build -t my-node-app .

      - name: Step 4 - Sucess message
        run: echo "Build Successfull !!!"


