name: CI/CD on EC2 Runner 👑

on:
  push:
    branches:
      - Ci-Cd

jobs:
  build-and-run:

    runs-on: self-hosted

    steps:

      - name: Checkout code 📥
        uses: actions/checkout@v4

      - name: Show files 📁
        run: ls -la

      - name: Build Docker image 🐳
        run: docker build -t my-node-app .

      - name: Stop old container (if running)
        run: docker stop my-node-app || true

      - name: Remove old container
        run: docker rm my-node-app || true

      - name: Run new container 🚀
        run: docker run -d -p 3000:3000 --name my-node-app my-node-app
